kind: Pod
apiVersion: v1
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  serviceAccountName: {{ include "mychart.serviceAccountName" . }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 8 }}
  containers:
    - name: {{ .Chart.Name }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      env:
        - name: SG_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: saasglue-agent
              key: accessKeyId
        - name: SG_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: saasglue-agent
              key: accessKeySecret
        {{- if .Values.tags }}
        - name: SG_TAGS
          value: {{ .Values.tags }}
        {{- end }}
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      # livenessProbe:
      #   httpGet:
      #     path: /
      #     port: http
      # readinessProbe:
      #   httpGet:
      #     path: /
      #     port: http
      resources:
        {{- toYaml .Values.resources | nindent 12 }}
  terminationGracePeriodSeconds: 20
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
