{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: saasglue-agent
subjects:
  - kind: ServiceAccount
    name: saasglue-agent
    namespace: {{.Release.Namespace}}
roleRef:
  kind: Role
  name: saasglue-agent
  apiGroup: rbac.authorization.k8s.io
{{- end }}