apiVersion: v1
kind: Secret
metadata:
  name: saasglue-agent
  namespace: {{.Values.namespace}}
type: "Opaque"
data:
  accessKeyId: {{default "" .Values.accessKeyId | b64enc | quote}}
  accessKeySecret: {{default "" .Values.accessKeySecret | b64enc | quote}}
